namespace Schematch.Core.Model;

public sealed class ColumnModel
{
    public string Name { get; set; } = "";
    public int Ordinal { get; set; }

    /// <summary>Provider-native type string, e.g. "nvarchar(50)" or "character varying(50)".</summary>
    public string DataType { get; set; } = "";

    public bool IsNullable { get; set; } = true;

    /// <summary>Default expression as reported by the engine (display form, not normalized).</summary>
    public string? DefaultExpression { get; set; }

    /// <summary>SQL Server names default constraints; needed to drop/alter them.</summary>
    public string? DefaultConstraintName { get; set; }

    /// <summary>Identity/generated clause in the provider's dialect, e.g. "IDENTITY(1,1)" or "GENERATED BY DEFAULT AS IDENTITY".</summary>
    public string? IdentityClause { get; set; }

    /// <summary>Expression for computed (SQL Server) / generated (PostgreSQL) columns.</summary>
    public string? ComputedExpression { get; set; }

    /// <summary>PERSISTED (SQL Server) / STORED (PostgreSQL) for computed columns.</summary>
    public bool IsPersisted { get; set; }

    /// <summary>Collation only when it differs from the database default.</summary>
    public string? Collation { get; set; }
}
