-- Schematch demo fixture: SOURCE database (PostgreSQL, desired state)
CREATE SCHEMA IF NOT EXISTS sales;

CREATE TABLE public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(255),
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uq_customers_email UNIQUE (email)
);

CREATE TABLE public.products (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(200) NOT NULL,
    sku character varying(50) NOT NULL,
    price numeric(18,4) NOT NULL DEFAULT 0,
    CONSTRAINT pk_products PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_products_sku ON public.products (sku);

CREATE TABLE sales.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id integer NOT NULL,
    order_date timestamp without time zone NOT NULL DEFAULT now(),
    total numeric(18,4) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'New',
    last_modified timestamp without time zone,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON DELETE CASCADE,
    CONSTRAINT ck_orders_total CHECK (total > 0)
);
CREATE INDEX ix_orders_customer_id ON sales.orders (customer_id);

CREATE FUNCTION public.fn_customer_order_count(p_customer_id integer)
RETURNS integer
LANGUAGE sql
AS $$ SELECT count(*)::integer FROM sales.orders WHERE customer_id = p_customer_id $$;

CREATE VIEW public.vw_customer_orders AS
SELECT c.id AS customer_id, c.name, o.id AS order_id, o.order_date, o.total, o.status
FROM public.customers c
JOIN sales.orders o ON o.customer_id = c.id;

CREATE PROCEDURE sales.p_noop()
LANGUAGE plpgsql
AS $$ BEGIN PERFORM 1; END $$;

CREATE FUNCTION sales.trg_orders_touch()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.last_modified := now();
    RETURN NEW;
END
$$;

CREATE TRIGGER trg_orders_touch
BEFORE UPDATE ON sales.orders
FOR EACH ROW EXECUTE FUNCTION sales.trg_orders_touch();

INSERT INTO public.customers (id, name, email, created_at) VALUES
    (1, 'Alice', 'alice@example.com', '2026-01-01 08:00:00'),
    (2, 'Budi',  'budi@example.com',  '2026-01-02 08:00:00'),
    (3, 'Citra', 'citra@example.com', '2026-01-03 08:00:00'),
    (4, 'Dewi',  'dewi@example.com',  '2026-01-04 08:00:00'),
    (5, 'Eko',   'eko@example.com',   '2026-01-05 08:00:00');

INSERT INTO public.products (id, name, sku, price) VALUES
    (1, 'Widget', 'W-001', 19.9900),
    (2, 'Gadget', 'G-001', 49.5000);

INSERT INTO sales.orders (id, customer_id, order_date, total, status) VALUES
    (1, 1, '2026-02-01 10:00:00', 19.9900, 'Shipped'),
    (2, 2, '2026-02-02 11:00:00', 49.5000, 'New'),
    (3, 3, '2026-02-03 12:00:00', 69.4900, 'New');

SELECT setval(pg_get_serial_sequence('public.customers', 'id'), 10);
SELECT setval(pg_get_serial_sequence('public.products', 'id'), 10);
SELECT setval(pg_get_serial_sequence('sales.orders', 'id'), 10);
