-- Schematch demo fixture: TARGET database (PostgreSQL, drifted state)
-- Drift mirrors the SQL Server fixture:
--   customers: email varchar(200), no unique constraint, extra legacy_code column, no created_at default
--   orders:    total numeric(10,2), no check constraint, no ix_orders_customer_id, status default 'Pending'
--   products:  missing; obsolete_log: extra; view older; function/procedure/trigger missing
--   data: customer 5 missing, 6 extra, 3 different email; order 3 missing
CREATE SCHEMA IF NOT EXISTS sales;

CREATE TABLE public.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(200),
    created_at timestamp without time zone NOT NULL,
    legacy_code integer,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE sales.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id integer NOT NULL,
    order_date timestamp without time zone NOT NULL DEFAULT now(),
    total numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'Pending',
    last_modified timestamp without time zone,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON DELETE CASCADE
);

CREATE TABLE public.obsolete_log (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message character varying(400),
    CONSTRAINT pk_obsolete_log PRIMARY KEY (id)
);

CREATE VIEW public.vw_customer_orders AS
SELECT c.id AS customer_id, c.name, o.id AS order_id, o.order_date, o.total
FROM public.customers c
JOIN sales.orders o ON o.customer_id = c.id;

INSERT INTO public.customers (id, name, email, created_at, legacy_code) VALUES
    (1, 'Alice', 'alice@example.com',     '2026-01-01 08:00:00', NULL),
    (2, 'Budi',  'budi@example.com',      '2026-01-02 08:00:00', NULL),
    (3, 'Citra', 'citra.old@example.com', '2026-01-03 08:00:00', 7),
    (4, 'Dewi',  'dewi@example.com',      '2026-01-04 08:00:00', NULL),
    (6, 'Fajar', 'fajar@example.com',     '2026-01-06 08:00:00', NULL);

INSERT INTO sales.orders (id, customer_id, order_date, total, status) VALUES
    (1, 1, '2026-02-01 10:00:00', 19.99, 'Shipped'),
    (2, 2, '2026-02-02 11:00:00', 49.50, 'New');

SELECT setval(pg_get_serial_sequence('public.customers', 'id'), 10);
SELECT setval(pg_get_serial_sequence('sales.orders', 'id'), 10);
